. > trampod
.
.set maintypesize 9
.set typeface "Palatino"
.include "a5atl"
.
.bindfont 14 "atl/~~typeface-Bold" 14000
.bindfont 15 "atl/~~typeface-Bold" 12000
.
.usegreek
.
.parspace 1
.parindent 0
.justify
.
.cancelflag $chead
.cancelflag $shead
.cancelflag $sshead
.
.flag $chead "$f14" "$f"
.flag $shead "$f15" "$f"
.flag $sshead "$bf" "$unbf"

.set chapter -1
.set section -1
.set subsection -1
.
.nofoot
.copy
.goto 144.0
.
$c $f14 Archimedes TRAM Motherboard $f
.
.space
.
$c $f14 User Guide $f
.
.goto 414.0
.
Gnome Computers Ltd
25A Huntingdon St.
St. Neots
Cambridgeshire
PE19 1BG
.
.blank
.
Tel. (0480) 406164 $e Issue 1
.
.fill
.set sectname "Introduction"
.
.headlength 2
.head
~%page $e $it~!sectname$unit
.endh
.
.
.newpage
.
.footlength 1
.foot
$c--
.endf
.
.section Introduction

The TRAM motherboard (TMB) is a circuit card which plugs into the expansion
bus of the Acorn Archimedes computer. Its function is to house a number of
Transputer Modules (TRAMs) and to allow the Archimedes to communicate with
the Inmos transputer links of the TRAMs. This is achieved with the use of an
Inmos link adapter chip on the board. This chip has a register interface
which is mapped into the Archimedes' I/O address space. Data written to the
chip from the Archimedes may be sent down the link while data received from
the link may be read by the Archimedes.

The board can also be programmed to interrupt the Archimedes when the link
adapter has transmitted or received a byte of data or when an error occurs in
one of the transputers connected to the board.
.
.section Installation

The TMB card is a single Eurocard PCB measuring 100x160mm. It has a 64 way
connector at one end and a 37 way D connector and mounting panel at the other
end. The card contains static sensitive ICs and so appropriate precautions
should be taken while handling and installing it.

The card is installed by plugging it into a free slot in the expansion
backplane. There is no need to configure the card to respond to a particular
address as each slot has a distinct address range. The driving software will
normally scan all the slots to locate the appropriate podule.

The machine should be switched off while the installation is done. The lid of
the machine should be removed and the board plugged into a free slot in the
podule backplane. The rear panel can then be screwed down to secure the card
in the machine. Finally, the lid should be replaced and the installation is
then complete.

The TMB draws power from the +5V rail of the Archimedes and requires
approximately 200mA.
.
.section TRAM connections

The TMB can accommodate up to four size 1 TRAMs and the four connection
sites on the board are labelled TRAM 0 through TRAM 3. It is very important
that the TRAMs be plugged in the right way round. A triangular marker on the
board indicates pin 1 of the TRAM and this should be aligned with the
corresponding mark on the TRAM.

TRAM 0 is different from the others in that it also has a connector for
subsystem control signals. This site should be used for a TRAM which has a
subsystem control port.

.section System Control Signals

A transputer or group of transputers is normally controlled by three signals
called Reset, Analyse and Error. There are four sets of these signals on the
TMB which are called the Up, Down, Host and Subsystem ports. The Subsystem
port signals are generated by TRAM 0. The Host port signals are generated by
the host computer, in this case the Archimedes. The Up port signals come onto
the board via the 37 way connector and the Down port signals leave the board
on this connector. The Subsystem port may be used to control other TRAMs on
the board and also appears on the 37 way connector. These signals behave as
described in Inmos Technical note 49 (Module Motherboard Architecture).

Two links (LK3 and LK4) on the TMB control the action of the system control
signals. LK3 determines the source of control signals for the board as a
whole. If it is open, the Host port provides the control signals. When it is
closed, the control signals come from the Up port on the 37 way connector.
LK4 determines the source of control signals for TRAMs 1 through 3. If it is
open, the signals come from the subsystem port of TRAM 0. If it is closed the
signals come from either the Host or Up port depending on the state of LK3.
Where multiple boards are used, the Up port of one board should be connected
to either the Down or Subsystem ports of another board. See the Inmos note for
more details on controlling multiple boards.
.
.section Link Connections

The link connections of the TRAMs are arranged in a pipeline as described in
Inmos Technical Note 49. Link 1 of TRAM 0 is known as Pipehead and is connected
to the 37 way connector. Link 2 of TRAM 0 connects to link 1 of TRAM 1 and
this pattern repeats until, finally, link 2 of TRAM 3 (Pipetail) connects to
the 37 way connector. The remaining links on each TRAM (links 0 and 3) are
wired to the 37 way connector with the exception of TRAM 0 link 0.

The link adapter chip on the board has its link connection wired to two links
on the board labelled LK1 and LK2. From here the link may be routed to link 0
of TRAM0 by placing jumpers over the pairs of pins nearest the edge of the
board. With the jumpers over the pairs of pins nearest to the 37 way connector, link 0 of TRAM 0 is wired to the 37 way connector.
.
.ensure 15
.section Connector Pinout
.copy
.contig inline
.set ldept ~%linedepth
.linedepth 7.0
.space
.tabset 20r 24 30r 34
.
$t$t$t 1 $t GND
$t notUpReset $t 20
$t$t$t 2 $t notUpAnalyse
$t notUpError $t 21
$t$t$t 3 $t Tram0LinkOut0
$t Tram0LinkIn0 $t 22
$t$t$t 4 $t Tram0LinkOut3
$t Tram0LinkIn3 $t 23
$t$t$t 5 $t GND
$t Tram1LinkOut0 $t 24
$t$t$t 6 $t Tram1LinkIn0
$t Tram1LinkOut3 $t 25
$t$t$t 7 $t Tram1LinkIn3
$t Tram2LinkOut0 $t 26
$t$t$t 8 $t Tram2LinkIn0
$t GND $t 27
$t$t$t 9 $t Tram2LinkOut3
$t Tram2LinkIn3 $t 28
$t$t$t 10 $t Tram3LinkOut0
$t Tram3LinkIn0 $t 29
$t$t$t 11 $t Tram3LinkOut3
$t Tram3LinkIn3 $t 30
$t$t$t 12 $t GND
$t$t 31
$t$t$t 13
$t PipeHeadLinkOut $t 32
$t$t$t 14 $t PipeHeadLinkIn
$t notSubsystemReset $t 33
$t$t$t 15 $t notSubsystemAnalyse
$t notSubsystemError $t 34
$t$t$t 16 $t PipeTailLinkOut
$t PipeTailLinkIn $t 35
$t$t$t 17
$t$t 36
$t$t$t 18 $t notDownReset
$t notDownAnalyse $t 37
$t$t$t 19 $t notDownError
.
.space
.linedepth ~~ldept
.endc
.fill
.
.section Programming the TMB

It is assumed that the reader is familiar with the Acorn documentation for
podules ("A Series Podules", Acorn Computers, May 1987) and the Inmos data
sheet for the IMSC012 link adapter chip. All devices on the TMB are byte
wide and should therefore be accessed with byte (as opposed to word) cycles.

The TMB contains a podule identity (PI) ROM which is mapped into the PI
space. The ROM contains an extended (8 byte) PI as follows:
.
.tabset 10 20 35
.copy
.contig inline
.space
.
$t _Byte $t Content $t Comment_

$t 0 $t X'00' $t (X'01', X'04', X'05' )
$t 1 $t       $t (reserved)
$t 2 $t       $t (reserved)
$t 3 $t X'4B' $t Product type (low)
$t 4 $t X'00' $t Product type (high)
$t 5 $t X'0E' $t Manufacturer (low)
$t 6 $t X'00' $t Manufacturer (high)
$t 7 $t X'00' $t Country
.
.space
.endc
.fill
.
Bit 0 of byte 0 is a 1 when the TMB is generating an IRQ interrupt. Bit 2
of byte 0 is a 1 when the TMB is generating a FIQ interrupt.

The TMB is a Simple Podule and is thus accessed by cycles controlled by the
Archimedes' I/O controller chip. All devices on the TMB may be accessed
using fast cycles. In addition to the podule ID ROM the TMB contains an
Inmos C012 link adapter chip and a control/status
register (CSR). The four registers of the link adapter are mapped into
successive words in the I/O space and the CSR is mapped into the next word.
Thus, if the TMB is placed in podule slot 0 in the Archimedes the memory map
is as follows:
.
.copy
.contig inline
.space
.tabset 10 20 41c
.
$t _Address $t Content $t Access speed_

$t X'33C0000' $t PI byte 0    $t synchronous
$t X'33C0004' $t PI byte 1    $t "
$t . . .      $t . . .        $t "
$t X'33C001C' $t PI byte 7    $t "

$t X'3342000' $t C012 reg 0   $t fast
$t X'3342004' $t C012 reg 1   $t "
$t X'3342008' $t C012 reg 2   $t "
$t X'334200C' $t C012 reg 3   $t "
$t X'3342010' $t CSR          $t "
.
.space
.endc
.fill
.
This set of registers repeats at 8 word intervals throughout the podule
address space. To maintain compatability with future products of a similar
type, only the lowest set of addresses should be used.

The control status register contains 6 bits which may be written and one bit
which is read-only. The write bits are cleared to zero when the Archimedes'
reset line is asserted. When writing to the CSR, the unused bits  (6 to 7)
should be zero to maintain compatibility with other similar products.

The functions of the bits in this register are as follows

$bf Bit 0 - ResetOut$unbf. Writing a 1 asserts the reset line on the Host
control signal port.

$bf Bit 1 - AnalyseOut$unbf. Writing a 1 asserts the analyse line on 
the Host control signal port.

$bfBit 2 - LinkSpeed$unbf. Connected to the LinkSpeed pins of the link adapter
chip and the TRAMs. Writing a 1 causes the board to operate with a 20MHz link
speed. A zero causes a link speed of 10MHz.

$bfBit 3 - ChipReset$unbf. Writing a 1 asserts the reset line of the link
adapter chip. Normally asserted with ResetOut and may be useful if the chip
locks up because of a faulty link connection.

$bfBit 4 (READ) - ErrorIn$unbf. Reflects the state of the Error signal on the
Host control signal port. This bit is read-only and a 0 indicates the
presence of an error.

$bfBit 4 (WRITE) - IntMask$unbf. Writing a 1 allows the board to generate
interrupts. A 0 disables interrupt generation.

$bfBit 5 - IntType$unbf. Determines the type of interrupt generated by the
link adapter chip. A 0 generates IRQ interrupts while a 1 generates FIQ
interrupts when the link adapter has sent or received a byte.

The two interrupt signals of the link adapter chip are ORed together to
generate the IRQ or FIQ signal required by the Archimedes. Note that the 
host error signal always generates an IRQ interrupt.
.
